export const PARTY_QUESTIONS = [
  "Who is most likely to laugh at their own jokes?",
  "Who would survive longest in a zombie apocalypse?",
  "Who is most likely to become famous?",
  "Who takes the longest to get ready?",
  "Who would spend all their money on food?",
  "Who is most likely to start a cult?",
  "Who would be the worst roommate?",
  "Who is most likely to go viral for something embarrassing?",
  "Who would win in an argument with a brick wall?",
  "Who secretly has the best dance moves?",
  "Who would eat the weirdest food combination?",
  "Who is most likely to talk to strangers on the internet?",
  "Who would forget their own birthday?",
  "Who is most likely to be late to their own wedding?",
  "Who would binge-watch a show without telling anyone?",
  "Who is most likely to text the wrong person something embarrassing?",
  "Who would accidentally like a 3-year-old photo while stalking someone's profile?",
  "Who is most likely to fall asleep at a party?",
  "Who would spend 20 minutes deciding what to eat and then order the same thing as always?",
  "Who is most likely to reply 'you too' when a waiter says enjoy your meal?",
  "Who would get lost using Google Maps?",
  "Who is most likely to laugh at completely the wrong moment?",
  "Who would cry at a dog food commercial?",
  "Who is most likely to start a sentence with 'I'm not racist but...'?",
  "Who would wave back at someone who wasn't actually waving at them?",
  "Who is most likely to trip on a completely flat surface?",
  "Who would spend more time taking photos of food than eating it?",
  "Who is most likely to dramatically overreact to a minor inconvenience?",
  "Who would still be awake at 3am for absolutely no reason?",
  "Who is most likely to apologize to furniture they bumped into?",
  "Who would get personally offended by a bad WiFi connection?",
  "Who is most likely to have 47 unread messages right now?",
  "Who would bring up an argument from 3 years ago out of nowhere?",
  "Who is most likely to forget why they walked into a room?",
  "Who would spend an hour writing a text and then just send 'lol'?",
  "Who is most likely to dramatically narrate their own life out loud?",
  "Who would get genuinely competitive at a children's board game?",
  "Who is most likely to have a full conversation with their pet?",
  "Who would show up to the wrong venue for an event and not tell anyone?",
  "Who is most likely to google symptoms and convince themselves they're dying?",
]

export function pickRandomQuestions(count: number = 5): string[] {
  return [...PARTY_QUESTIONS].sort(() => Math.random() - 0.5).slice(0, count)
}
